AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Stock prices indexer

Globals:
  Function:
    Timeout: 240
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:

  PricesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Symbol"
          AttributeType: "S"
        - AttributeName: "Timestamp"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "Symbol"
          KeyType: "HASH"
        - AttributeName: "Timestamp"
          KeyType: "RANGE"
      TableName: "Prices"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  PriceIndexingFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          PRICES_TABLE_NAME: !Ref PricesTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref PricesTable
      Events:
        IndexSymbolPrices:
          Type: Api
          Properties:
            Path: /index/{symbol}
            Method: post
    Metadata:
      DockerTag: java21-gradle-v1
      DockerContext: ./PriceIndexingFunction
      Dockerfile: Dockerfile

  GetAveragePriceForStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          PRICES_TABLE_NAME: !Ref PricesTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PricesTable
      Events:
        GetAveragePriceForStock:
          Type: Api
          Properties:
            Path: /average/{symbol}/{from}/{to}
            Method: get
    Metadata:
      DockerTag: java21-gradle-v1
      DockerContext: ./GetAveragePriceForStockFunction
      Dockerfile: Dockerfile

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  PriceIndexingApi:
    Description: API Gateway endpoint URL for Prod stage for Price indexing function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/index/{symbol}"
  GetAveragePriceForStockAou:
    Description: API Gateway endpoint URL for Prod stage for Get average price for stock function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/average/{symbol}/{from}/{to}"
  PriceIndexingFunction:
    Description: Price indexing Lambda Function ARN
    Value: !GetAtt PriceIndexingFunction.Arn
  GetAveragePriceForStockFunction:
    Description: Get average price for stock Lambda Function ARN
    Value: !GetAtt GetAveragePriceForStockFunction.Arn
  PriceIndexingFunctionIamRole:
    Description: Implicit IAM Role created for PriceIndexingFunction
    Value: !GetAtt PriceIndexingFunction.Arn
  GetAveragePriceForStockFunctionIamRole:
    Description: Implicit IAM Role created for Get average price for stock Lambda Function
    Value: !GetAtt GetAveragePriceForStockFunction.Arn
